name: Libray Publishing

#Execute on tag push
on:
  push:
    tags:
      - v*

jobs:
  # Publish package to artifact hosts
  artifact-publish:
    name: Artifact Publish
    runs-on: ubuntu-latest

    #Executing the job
    steps:
      # Copy repository
      - uses: actions/checkout@v2
      #Setup jdk
      - name: Setup jdk 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Add execute permission
        run: chmod +x ./gradlew

      # Execute gradle publishing
      - name: Gradle publish
        run: ./gradlew publish
